// Common Korean grammar points, so the catalog starts with clean names and
// the first saves match without a model call. Forms follow the Learn guides'
// meta.grammar forms where a guide exists. Level: 1 beginner .. 5 advanced.
module.exports = [
    // Particles
    { key: 'ko.particle.topic', form: '은/는', name: 'Topic particle', level: 1 },
    { key: 'ko.particle.subject', form: '이/가', name: 'Subject particle', level: 1 },
    { key: 'ko.particle.object', form: '을/를', name: 'Object particle', level: 1 },
    { key: 'ko.particle.e', form: '에', name: 'Place, time and direction (at, to)', level: 1 },
    { key: 'ko.particle.eseo', form: '에서', name: 'Place of an action; from', level: 1 },
    { key: 'ko.particle.do', form: '도', name: 'Also, too', level: 1 },
    { key: 'ko.particle.uy', form: '의', name: 'Possessive (of)', level: 1 },
    { key: 'ko.particle.wa-gwa', form: '와/과', name: 'And, with (formal)', level: 1 },
    { key: 'ko.particle.hago', form: '하고', name: 'And, with', level: 1 },
    { key: 'ko.particle.rang', form: '(이)랑', name: 'And, with (casual)', level: 2 },
    { key: 'ko.particle.ege', form: '에게/한테', name: 'To (a person)', level: 2 },
    { key: 'ko.particle.buteo', form: '부터', name: 'From (a starting point)', level: 2 },
    { key: 'ko.particle.kkaji', form: '까지', name: 'Until, up to', level: 2 },
    { key: 'ko.particle.ro', form: '(으)로', name: 'By means of, toward', level: 2 },
    { key: 'ko.particle.man', form: '만', name: 'Only', level: 2 },
    { key: 'ko.particle.boda', form: '보다', name: 'Than (comparison)', level: 2 },
    { key: 'ko.particle.kkeseo', form: '께서', name: 'Honorific subject particle', level: 3 },
    // Endings and tenses
    { key: 'ko.ending.ayo-eoyo', form: '-아요/어요', name: 'Polite present ending', level: 1 },
    { key: 'ko.ending.ieyo-yeyo', form: '-이에요/예요', name: 'To be (polite)', level: 1 },
    { key: 'ko.ending.seumnida', form: '-습니다/ㅂ니다', name: 'Formal polite ending', level: 2 },
    { key: 'ko.tense.past', form: '-았/었-', name: 'Past tense', level: 1 },
    { key: 'ko.tense.future-geoyeyo', form: '-(으)ㄹ 거예요', name: 'Future and plans (will)', level: 2 },
    { key: 'ko.ending.lgeyo', form: '-(으)ㄹ게요', name: 'I will (promise to the listener)', level: 2 },
    { key: 'ko.ending.go-isseoyo', form: '-고 있다', name: 'Progressive (be doing)', level: 2 },
    { key: 'ko.ending.seyo', form: '-(으)세요', name: 'Polite request (please do)', level: 1 },
    { key: 'ko.honorific.si', form: '-(으)시-', name: 'Honorific verb marker', level: 3 },
    { key: 'ko.ending.jiyo', form: '-지요/죠', name: 'Right? (seeking agreement)', level: 2 },
    { key: 'ko.ending.neyo', form: '-네요', name: 'Surprise or realization', level: 2 },
    { key: 'ko.ending.bsida', form: '-(으)ㅂ시다', name: "Let's (formal)", level: 2 },
    { key: 'ko.ending.ja', form: '-자', name: "Let's (casual)", level: 2 },
    { key: 'ko.ending.lkkayo', form: '-(으)ㄹ까요', name: 'Shall we? / I wonder', level: 2 },
    { key: 'ko.ending.neunde-ending', form: '-는데요', name: 'Soft ending (background, hesitation)', level: 3 },
    { key: 'ko.ending.geodeun', form: '-거든요', name: 'You see (giving a reason)', level: 3 },
    // Wanting, ability, obligation
    { key: 'ko.expr.go-sipda', form: '-고 싶다', name: 'Want to', level: 1 },
    { key: 'ko.expr.l-su-itda', form: '-(으)ㄹ 수 있다/없다', name: 'Can / cannot', level: 2 },
    { key: 'ko.expr.aya-hada', form: '-아야/어야 하다', name: 'Have to, must', level: 2 },
    { key: 'ko.expr.a-boda', form: '-아/어 보다', name: 'Try doing', level: 2 },
    { key: 'ko.expr.a-juda', form: '-아/어 주다', name: 'Do something for someone', level: 2 },
    { key: 'ko.expr.ji-anta', form: '-지 않다', name: 'Do not (long negation)', level: 1 },
    { key: 'ko.neg.an', form: '안', name: 'Do not (short negation)', level: 1 },
    { key: 'ko.neg.mot', form: '못', name: 'Cannot (short negation)', level: 1 },
    { key: 'ko.expr.ji-mada', form: '-지 마세요', name: "Please don't", level: 2 },
    { key: 'ko.expr.ji-mothada', form: '-지 못하다', name: 'Cannot (long negation)', level: 2 },
    { key: 'ko.expr.n-jeok-itda', form: '-(으)ㄴ 적이 있다', name: 'Have done before (experience)', level: 3 },
    { key: 'ko.expr.ge-doeda', form: '-게 되다', name: 'End up, come to (do)', level: 3 },
    { key: 'ko.expr.a-jida', form: '-아/어지다', name: 'Become (change of state)', level: 3 },
    { key: 'ko.expr.neun-geot-gatda', form: '-(으)ㄴ/는 것 같다', name: 'It seems, I think', level: 3 },
    // Connectors
    { key: 'ko.conn.go', form: '-고', name: 'And (linking actions)', level: 1 },
    { key: 'ko.conn.jiman', form: '-지만', name: 'But', level: 1 },
    { key: 'ko.conn.aseo', form: '-아서/어서', name: 'So, because; and then', level: 2 },
    { key: 'ko.conn.nikka', form: '-(으)니까', name: 'Because, since (before a suggestion)', level: 2 },
    { key: 'ko.conn.neunde', form: '-는데', name: 'But, and (background)', level: 2 },
    { key: 'ko.conn.myeon', form: '-(으)면', name: 'If, when', level: 2 },
    { key: 'ko.conn.myeonseo', form: '-(으)면서', name: 'While (at the same time)', level: 3 },
    { key: 'ko.conn.reo', form: '-(으)러', name: 'In order to (go/come)', level: 2 },
    { key: 'ko.conn.ryeogo', form: '-(으)려고', name: 'In order to, intending to', level: 3 },
    { key: 'ko.conn.ado', form: '-아도/어도', name: 'Even if', level: 3 },
    { key: 'ko.conn.gi-ttaemune', form: '-기 때문에', name: 'Because (formal)', level: 2 },
    { key: 'ko.conn.l-ttae', form: '-(으)ㄹ 때', name: 'When', level: 2 },
    { key: 'ko.conn.gi-jeone', form: '-기 전에', name: 'Before doing', level: 2 },
    { key: 'ko.conn.n-hue', form: '-(으)ㄴ 후에', name: 'After doing', level: 2 },
    { key: 'ko.conn.dorok', form: '-도록', name: 'So that', level: 4 },
    // Modifiers and nouns from verbs
    { key: 'ko.mod.neun', form: '-는', name: 'Present modifier (that does)', level: 3 },
    { key: 'ko.mod.n', form: '-(으)ㄴ', name: 'Past or adjective modifier', level: 3 },
    { key: 'ko.mod.l', form: '-(으)ㄹ', name: 'Future modifier', level: 3 },
    { key: 'ko.nom.gi', form: '-기', name: 'Verb as a noun (-ing)', level: 3 },
    { key: 'ko.nom.geot', form: '-는 것', name: 'The act of (doing)', level: 3 },
    // Quoting and speech
    { key: 'ko.quote.dago', form: '-다고 하다', name: 'Indirect quotation (says that)', level: 4 },
    { key: 'ko.speech.banmal', form: '반말', name: 'Casual speech', level: 2 },
];
