// Role-play scenes for Speak. Each scene gives Horang a role, a setting and
// two or three goals the learner works through out loud. Text here is in
// English; Horang plays the scene in whatever language the learner studies.
// `korea` adds local flavor when the learner studies Korean.

const SCENARIOS = [
    {
        id: 'cafe',
        character: 'horang',
        title: 'Order at a café',
        blurb: 'Grab an iced americano from Horang, the barista.',
        level: 'beginner',
        background: 'cafe',
        role: 'a cheerful barista at a small neighborhood café',
        korea: 'The café is called 까치 카페, in a quiet Seoul alley. An iced americano is 4,000 won.',
        goals: ['Order a drink', 'Ask for it to go', 'Ask how much it costs'],
        phrases: { ko: ['아이스 아메리카노 하나 주세요', '포장해 주세요', '얼마예요?'] },
    },
    {
        id: 'store',
        character: 'horang',
        title: 'Convenience store run',
        blurb: 'Find ramyeon, get a bag and pay at the counter.',
        level: 'beginner',
        background: 'store',
        role: 'a sleepy but friendly late-night convenience store clerk',
        korea: 'A Korean 편의점 at night. Bags cost 100 won. Cup ramyeon is in aisle 2.',
        goals: ['Ask where something is', 'Ask for a bag', 'Pay by card'],
        phrases: { ko: ['라면 어디 있어요?', '봉투 주세요', '카드로 할게요'] },
    },
    {
        id: 'taxi',
        character: 'horang',
        title: 'Take a taxi',
        blurb: 'Tell the driver where to go without getting lost.',
        level: 'beginner',
        background: 'taxi',
        role: 'a chatty taxi driver who loves giving food recommendations',
        korea: 'A Seoul taxi at dusk. The learner wants to go to Myeongdong station.',
        goals: ['Say where you want to go', 'Ask how long it takes', 'Ask to stop here'],
        phrases: { ko: ['명동역으로 가 주세요', '얼마나 걸려요?', '여기서 세워 주세요'] },
    },
    {
        id: 'friend',
        character: 'sora',
        title: 'Make a new friend',
        blurb: 'Sora just moved to Seoul. Meet her by the Han river and make plans.',
        level: 'beginner',
        background: 'park',
        role: 'yourself, Sora, newly arrived in Seoul from the countryside, sitting on the next picnic mat and meeting the learner for the first time',
        korea: 'A sunny afternoon at a Han River park in Seoul.',
        goals: ['Introduce yourself', 'Ask what they like to do', 'Make plans to meet again'],
        phrases: { ko: ['저는 ___예요', '뭐 좋아해요?', '다음에 같이 ___ 할래요?'] },
    },
    {
        id: 'pocha',
        character: 'horang',
        title: 'Dinner at a street tent',
        blurb: 'Ask for a recommendation, handle the spice, get the bill.',
        level: 'intermediate',
        background: 'pocha',
        role: 'the owner of a lively street tent restaurant who is proud of the food',
        korea: 'A 포장마차 at night. Tteokbokki is very spicy. The bill is paid at the end.',
        goals: ['Ask what is good here', 'Say how spicy you can handle', 'Ask for the bill'],
        phrases: { ko: ['뭐가 맛있어요?', '덜 맵게 해 주세요', '계산해 주세요'] },
    },
    {
        id: 'kdrama',
        character: 'horang',
        title: 'K-drama rooftop confession',
        blurb: 'Horang overacts a K-drama scene. Can you keep up?',
        level: 'intermediate',
        background: 'rooftop',
        role: 'a hilariously over-the-top K-drama lead on a rooftop at night, playing the scene for laughs (keep it wholesome and comedic, never actually romantic or flirtatious toward the learner)',
        korea: 'Classic drama tropes: dramatic pauses, wind in the hair, a sudden plot twist (a secret twin, amnesia, or a long-lost chaebol family).',
        goals: ['Tell them how you feel', 'React to the plot twist', 'Deliver a dramatic last line'],
        phrases: { ko: ['할 말이 있어요', '말도 안 돼!', '가지 마세요!'] },
    },
    {
        id: 'free',
        character: 'horang',
        title: 'Ask Horang anything',
        blurb: 'Free conversation. Ask questions and practice your saved words.',
        level: 'any',
        background: 'study',
        role: 'yourself, Horang the tutor, chatting in your hanok study room',
        korea: '',
        goals: ['Use three of your saved words', 'Ask Horang a question about the language'],
        phrases: { ko: ['이거 무슨 뜻이에요?', '다시 한번 말해 주세요', '천천히 말해 주세요'] },
        free: true,
    },

    {
        id: 'concert',
        character: 'sora',
        title: 'Concert merch line',
        blurb: 'Sora\'s first ever concert. Queue for merch and fangirl in Korean.',
        level: 'beginner',
        background: 'concert',
        role: 'yourself, Sora, at your very first concert since moving to Seoul, waiting in the merch line next to the learner and taking it very seriously (the group is a made-up one called "STARLIGHT"; never name real idols)',
        korea: 'Outside a Seoul arena before the show. Lightsticks cost 45,000 won.',
        goals: ['Say who your favorite member is', 'Ask what Sora is buying', 'Cheer together in Korean'],
        phrases: { ko: ['제 최애는 ___예요', '뭐 살 거예요?', '화이팅!'] },
    },
    {
        id: 'shop',
        character: 'sora',
        title: 'Shopping in Hongdae',
        blurb: 'Sora\'s new part-time job. Find your size and haggle a little.',
        level: 'intermediate',
        background: 'shop',
        role: 'yourself, Sora, a few weeks into a part-time job at a trendy clothing shop in Hongdae, still learning the trendy words but very earnest',
        korea: 'Hoodies are 39,000 won. You can give a small discount if they ask nicely.',
        goals: ['Ask to try something on', 'Ask for a different size', 'Ask for a discount'],
        phrases: { ko: ['입어 봐도 돼요?', '더 큰 사이즈 있어요?', '좀 깎아 주세요'] },
    },
    {
        id: 'palace',
        character: 'sora',
        title: 'Hanbok day at the palace',
        blurb: 'Sora shows you the palace. Rent a hanbok and ask a stranger for a photo.',
        level: 'beginner',
        background: 'palace',
        role: 'yourself, Sora (already in your own hanbok, as always), spending the day at Gyeongbokgung with the learner, who rents one (you also briefly play a friendly passer-by when they ask for a photo)',
        korea: 'People wearing hanbok get into the palace for free.',
        goals: ['Compliment Sora\'s hanbok', 'Ask someone to take a photo', 'Say thank you politely'],
        phrases: { ko: ['한복 진짜 예뻐요!', '사진 좀 찍어 주세요', '감사합니다'] },
    },
    {
        id: 'sorafree',
        character: 'sora',
        title: 'Hang out with Sora',
        blurb: 'Chat about anything: her village, Seoul surprises, food, dramas.',
        level: 'any',
        background: 'park',
        role: 'yourself, Sora, hanging out with the learner',
        korea: '',
        goals: ['Tell Sora about your week', 'Ask Sora a question'],
        phrases: { ko: ['요즘 뭐 봐요?', '저도요!', '진짜요?'] },
        free: true,
    },
];

const LEVELS = ['beginner', 'intermediate', 'advanced'];

const findScenario = (id) => SCENARIOS.find((s) => s.id === id) || null;

// What the browser needs to draw the scene picker.
const publicScenario = (s, language) => ({
    id: s.id,
    character: s.character || 'horang',
    title: s.title,
    blurb: s.blurb,
    level: s.level,
    background: s.background,
    goals: s.goals,
    phrases: (s.phrases && s.phrases[language]) || [],
});

module.exports = { SCENARIOS, LEVELS, findScenario, publicScenario };
